name = "my-app"
main = "src/index.ts"
compatibility_date = "2025-01-25"

compatibility_flags = [ "nodejs_compat" ]

# The following env vars must be set in `<project-root>/.dev.vars`
# [vars]
# JWT_SECRET_KEY = "your-secret-key-here"
# ADMIN_USERNAME = "your-admin-username"
# ADMIN_PASSWORD = "your-admin-password"
# SALT_ROUNDS = 8

[[kv_namespaces]]
binding = "USERS"
id = "c584c6b5cd4441d8b469e0d1b1317028"

[[kv_namespaces]]
binding = "MOVIES"
id = "ec4bc9465a1b43f2827950e614cba7fe"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1